// Service-worker runtime caching rules (FE-09, FE-11, W1-14).
//
// CRITICAL: any /api/ endpoint can return customer PII, financial data,
// design IP or insurance valuations (see CLAUDE.md "Data Privacy Rules").
// None of that may persist in Cache Storage on a shared bench tablet after
// the goldsmith logs out, and none of it may be served to a *different*
// logged-in user from a stale cache entry — that would bypass role-based
// filtering entirely (e.g. a VIEWER served an ADMIN's cached pricing).
//
// The previous config cached `/api/v1/orders` and `/api/v1/materials` with
// NetworkFirst (customer names + prices persisted in Cache Storage for 5-10
// minutes after logout) and `/api/v1/activities` with CacheFirst (a newly
// created activity could take up to an hour to appear). This module is the
// single source of truth `vite.config.ts` consumes, so there is exactly one
// place to audit for what the service worker is allowed to cache.
import type { RuntimeCaching } from 'workbox-build';

const NETWORK_TIMEOUT_SECONDS = 10;
const TEN_MINUTES_SECONDS = 10 * 60;
const THIRTY_DAYS_SECONDS = 30 * 24 * 60 * 60;
const ACTIVITIES_MAX_ENTRIES = 100;
const STATIC_ASSET_MAX_ENTRIES = 100;

/**
 * Labour activity categories ("Polieren", "Fassen", ...) carry no customer
 * PII, pricing or design IP, so a short, stale-tolerant cache is acceptable
 * for offline use. NetworkFirst — not CacheFirst — so a fresh network
 * response always wins when the device is online; the cache only serves a
 * recently-created activity for up to 10 minutes without a network, instead
 * of up to an hour.
 */
const ACTIVITIES_PATTERN = /\/api\/v1\/activities/;

/**
 * Every other `/api/` request — orders, customers, materials, invoices,
 * quotes, repairs, valuations, scrap-gold, time-tracking, users, auth, ... —
 * can carry PII, financial data, design IP or insurance valuations.
 * NetworkOnly, always: nothing is written to Cache Storage, so there is
 * nothing to leak to the next user of a shared tablet and nothing stale to
 * silently serve in place of a real request.
 */
const ALL_OTHER_API_PATTERN = /\/api\//;

/** Hashed build output (JS/CSS/fonts) — no user data, safe to cache long. */
const STATIC_ASSET_PATTERN = /\.(js|css|woff2?)(\?.*)?$/;

/**
 * Built by `vite.config.ts` and handed to `vite-plugin-pwa`'s
 * `workbox.runtimeCaching`. Order matters: Workbox uses first-match-wins,
 * so the specific activities rule must precede the `/api/` catch-all.
 */
export function buildRuntimeCaching(): RuntimeCaching[] {
  return [
    {
      urlPattern: ACTIVITIES_PATTERN,
      handler: 'NetworkFirst',
      options: {
        cacheName: 'api-activities',
        networkTimeoutSeconds: NETWORK_TIMEOUT_SECONDS,
        expiration: {
          maxEntries: ACTIVITIES_MAX_ENTRIES,
          maxAgeSeconds: TEN_MINUTES_SECONDS,
        },
        cacheableResponse: {
          statuses: [0, 200],
        },
      },
    },
    {
      // Never cache mutations, auth, or any PII/financial-bearing response.
      urlPattern: ALL_OTHER_API_PATTERN,
      handler: 'NetworkOnly',
    },
    {
      urlPattern: STATIC_ASSET_PATTERN,
      handler: 'CacheFirst',
      options: {
        cacheName: 'static-assets',
        expiration: {
          maxEntries: STATIC_ASSET_MAX_ENTRIES,
          maxAgeSeconds: THIRTY_DAYS_SECONDS,
        },
      },
    },
  ];
}

/**
 * Resolves which rule from {@link buildRuntimeCaching} would handle a given
 * request URL, using the same first-match-wins semantics Workbox's router
 * applies at runtime. Exported for tests only — the real service worker is
 * generated by `vite-plugin-pwa` from `buildRuntimeCaching()` directly and
 * never calls this.
 */
export function resolveCachingRule(url: string): RuntimeCaching | undefined {
  return buildRuntimeCaching().find((rule) => {
    if (rule.urlPattern instanceof RegExp) {
      return rule.urlPattern.test(url);
    }
    if (typeof rule.urlPattern === 'string') {
      return url.includes(rule.urlPattern);
    }
    // RouteMatchCallback is not used by any rule in this config.
    return false;
  });
}
